DEBUG_ENABLED = true;
GAME_RUNNING = true;
CTI_SECTOR_LOCATIONS = [];
SECTOR_ACTIVATION_SCRIPTS = [];
ONE_SECOND_HEARTBEATS = [];
ACTIVATION_RANGE = 1000;
SECTOR_RANGE = 600;
PRESENCE_MANAGER_RUNNING = false;